[package]
name = "racker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# logging
log = "0.4"
fern = { version = "0.6", features = ["colored"] }

# time
chrono = "0.4"

# config
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6"
xml-rs = "0.8"

# racker
racker-common = { path = "racker-common" }


[workspace]
members = [ "racker-daemon", "racker-common" ]
